### ISSUE TITLE
Refactor snake_case variable names to camelCase

### ISSUE THREAD

**Issue by malwaredllc** [malwaredllc/minicache#15]
Refactor snake_case variable names to camelCase

**Comment by adesokanayo** [comment]
I can pick this up to start contributing to this project .

**Comment by malwaredllc** [comment]
@adesokanayo that would be awesome!

**Comment by malwaredllc** [comment]
@adesokanayo Are you still planning on working on this? If not I am going to do it I think

**Comment by adesokanayo** [comment]
I already did. I made a PR but I'm unable to run the tests.

**Comment by malwaredllc** [comment]
Completed by #16
