### ISSUE TITLE
Make using TLS optional

### ISSUE THREAD

**Issue by malwaredllc** [malwaredllc/minicache#5]
Currently using TLS is required - if the TLS certificates do not exist in the `certs/` directory, or if the node's current hostname/IP is not listed in the TLS certificate SANs (subject alternate names), then the connection will fail at the TLS step.

Using TLS should be optional, perhaps with a command line flag when launching the server, or as a value in a config file.

**Comment by alvinlee001** [comment]
HI @malwaredllc, i think i managed to make this work as well, with either command line parameter flag
`--client-auth=false` with default of value `true`, and also available in json file as `client_auth`... it should work both on gRPC and REST.

**Comment by malwaredllc** [comment]
Closed by #7
